version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: crypto_simulation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-volume:/data/postgres/:/var/lib/postgresql/data
  
volumes:
  db-volume:


